// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwcviwzwedljuuyfduso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3Y3Zpd3p3ZWRsanV1eWZkdXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTExMDAsImV4cCI6MjA1OTE4NzEwMH0.p7nzS3bQiitHwtN4Sl3mZjO4z7mSWAqKgyyw209eObs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);